"""Theme generator utility — scaffold theme files from brand colors."""
from __future__ import annotations
from pathlib import Path

_COLORS_TEMPLATE = '''"""Auto-generated color scheme."""
from fasttailwind.contracts import ColorScheme


class Colors(ColorScheme):
    """Color scheme generated by fasttailwind.utils.generate_theme()."""
    primary = "{primary}"
    secondary = "{secondary}"
    accent = "{tertiary}"
    bg_base = "{secondary}-950"
    bg_surface = "{secondary}-900"
    bg_elevated = "{secondary}-800"
    bg_overlay = "{secondary}-700"
    text_primary = "{secondary}-50"
    text_secondary = "{secondary}-300"
    text_muted = "{secondary}-500"
    text_disabled = "{secondary}-600"
    border_default = "{secondary}-700"
    border_strong = "{secondary}-500"
    border_focus = "{primary}-500"
    success = "{tertiary}-500"
    warning = "amber-500"
    danger = "red-500"
    info = "blue-500"
'''

_TYPOGRAPHY_TEMPLATE = '''"""Auto-generated typography scheme."""
from fasttailwind.contracts import TypographyScheme


class Typography(TypographyScheme):
    """Typography scheme generated by fasttailwind.utils.generate_theme()."""
    font_sans = "font-sans"
    font_mono = "font-mono"
    size_xs = "text-xs"
    size_sm = "text-sm"
    size_base = "text-base"
    size_lg = "text-lg"
    size_xl = "text-xl"
    size_2xl = "text-2xl"
    size_3xl = "text-3xl"
    weight_normal = "font-normal"
    weight_medium = "font-medium"
    weight_bold = "font-bold"
    leading_tight = "leading-tight"
    leading_normal = "leading-normal"
    leading_relaxed = "leading-relaxed"
'''

_THEME_TEMPLATE = '''"""Auto-generated master theme."""
from fasttailwind.contracts import ThemeScheme
from .colors import Colors
from .typography import Typography


class Theme(ThemeScheme):
    """Master theme generated by fasttailwind.utils.generate_theme()."""
    colors = Colors()
    typography = Typography()
    space_xs = "1"
    space_sm = "2"
    space_md = "4"
    space_lg = "6"
    space_xl = "8"
    space_2xl = "12"
    radius_sm = "rounded"
    radius_md = "rounded-lg"
    radius_lg = "rounded-xl"
    radius_full = "rounded-full"
    breakpoints = {{"sm": "sm", "md": "md", "lg": "lg", "xl": "xl"}}
    button_variants = {{
        "primary": "bg-{primary}-600 text-white hover:bg-{primary}-500 focus:ring-{primary}-500",
        "secondary": "bg-{secondary}-800 text-{secondary}-100 hover:bg-{secondary}-700 focus:ring-{secondary}-500",
        "ghost": "bg-transparent text-{secondary}-300 hover:bg-{secondary}-800 focus:ring-{secondary}-500",
        "danger": "bg-red-600 text-white hover:bg-red-500 focus:ring-red-500",
    }}
    button_sizes = {{
        "sm": "px-3 py-1.5 text-sm",
        "md": "px-4 py-2 text-base",
        "lg": "px-6 py-3 text-lg",
    }}
    card_variants = {{
        "default": "bg-{secondary}-900 border border-{secondary}-800",
        "elevated": "bg-{secondary}-800 border border-{secondary}-700 shadow-lg",
        "ghost": "bg-transparent border border-{secondary}-800",
    }}
    badge_variants = {{
        "success": "bg-{tertiary}-900 text-{tertiary}-300 border border-{tertiary}-700",
        "warning": "bg-amber-900 text-amber-300 border border-amber-700",
        "danger": "bg-red-900 text-red-300 border border-red-700",
        "info": "bg-blue-900 text-blue-300 border border-blue-700",
        "neutral": "bg-{secondary}-800 text-{secondary}-300 border border-{secondary}-700",
    }}
    input_variants = {{
        "default": (
            "bg-{secondary}-800 border border-{secondary}-700 text-{secondary}-100 "
            "placeholder:text-{secondary}-500 focus:border-{primary}-500 focus:ring-1 "
            "focus:ring-{primary}-500"
        ),
        "error": (
            "bg-{secondary}-800 border border-red-500 text-{secondary}-100 "
            "focus:border-red-400 focus:ring-1 focus:ring-red-400"
        ),
    }}
    alert_variants = {{
        "success": "bg-{tertiary}-950 border border-{tertiary}-800 text-{tertiary}-200",
        "warning": "bg-amber-950 border border-amber-800 text-amber-200",
        "danger": "bg-red-950 border border-red-800 text-red-200",
        "info": "bg-blue-950 border border-blue-800 text-blue-200",
    }}
'''


def generate_theme(
    output_dir: str,
    *,
    primary: str,
    secondary: str,
    tertiary: str,
    mode: str = "dark",
) -> None:
    """Scaffold a complete theme from brand colors."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    fmt = {"primary": primary, "secondary": secondary, "tertiary": tertiary, "mode": mode}
    (out / "colors.py").write_text(_COLORS_TEMPLATE.format(**fmt))
    (out / "typography.py").write_text(_TYPOGRAPHY_TEMPLATE.format(**fmt))
    (out / "theme.py").write_text(_THEME_TEMPLATE.format(**fmt))
